# Change these first
owner: ahopkins
repo:  example-status-page

sites:
  - name: Sanic Book
    url: https://sanicbook.com/
  
status-website:
  baseUrl: /example-status-page
  logoUrl: https://raw.githubusercontent.com/sanic-org/sanic-assets/main/svg/sanic-framework-logo-circle.svg
  name: Sample Status Page
  introTitle: "This is an **example**."
  introMessage: Some info here...
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Sanic Docs
      href: https://sanic.dev/en/
